### ISSUE TITLE
TetGen - edge adjacent tet list

### ISSUE THREAD

**Issue by dnkrtz** [inducer/meshpy#20]
In the src/cpp/tetgen files I see the "edgeadjtetlist" that is set as it should be when the -nn switch is set, but I can't seem to find where this data gets dumped on the Python side. How can I access it?

Thanks!

**Comment by inducer** [comment]
Exposed in git. Let me know if that does what you need.

**Comment by dnkrtz** [comment]
Fantastic, that works. Awesome work on this, by the way.
