### ISSUE TITLE
Error on Install

### ISSUE THREAD

**Issue by vserluco** [inducer/meshpy#31]
![screen shot 2018-03-01 at 10 39 05 am](https://user-images.githubusercontent.com/1564854/36862826-dcbd5d56-1d3c-11e8-9170-3156f260ece6.png)

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

**Comment by vserluco** [comment]
No problem.  Thanks for pointing me in the direction of help.  It's weird that my traingle.so import is having issues.

File "/Users/serlucov/anaconda/envs/py27/lib/python2.7/site-packages/meshpy/triangle.py", line 4, in <module>
    import meshpy._triangle as internals
ImportError: dlopen(/Users/serlucov/anaconda/envs/py27/lib/python2.7/site-packages/meshpy/_triangle.so, 2): Symbol not found: __ZNSt8__detail15_List_node_base7_M_hookEPS0_
  Referenced from: /Users/serlucov/anaconda/envs/py27/lib/python2.7/site-packages/meshpy/_triangle.so
  Expected in: /usr/lib/libstdc++.6.dylib
 in /Users/serlucov/anaconda/envs/py27/lib/python2.7/site-packages/meshpy/_triangle.so
