### ISSUE TITLE
tet module does not compute mesh after calling "build"

### ISSUE THREAD

**Issue by skohlbr** [inducer/meshpy#32]
I have a huge model as a KML file which has been extracted from CAD data (don't ask ;) ). To get a mesh representation I parse the KML manually and collect all the polygon information, writing it out to .stl. This works fine for most polys as they have 3 or 4 vertices, which can be written to .stl directly. 30% of the model are polygons with > 4 vertices, however. My intent was to throw those polygons to meshpy and let it build tri-meshes for the polygons. Here's a code excerpt:
```
              mesh_info = MeshInfo()
              
              mesh_info.set_points(vertices)
            
              # Add a single facet with all the vertices
              mesh_info.set_facets([list(range(0,len(vertices)))])
              print '-----'
              mesh_info.dump()
              print '-----'
              
              mesh = build(mesh_info)
              
              mesh.dump()
```

and this is example output:

```
-----
array points: 5 elements, 3 values per element
  0: 0.00190297736144,0.00352662518731,15.4685
  1: 0.00190145604044,0.00352675828543,15.4684
  2: 0.00190145606727,0.00352675833519,15.3784
  3: 0.0019029773883,0.00352662523708,15.3785
  4: 0.00190297736144,0.00352662518731,15.4685
-----
array points: 0 elements, 3 values per element
```

My expectation was to get some mesh back with multiple facets, but instead the mesh has 0 elements after 'build' was called. It appears the MeshInfo input looks plausible. I hence have two questions:

- Does my approach make sense or did I miss something and what I try isn't what the 'tet' module is supposed to do?

- Would it be possible to provide some output and/or documentation on why just something empty is returned such as in my case? This would make it easier to understand what to look for.

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

You could try setting the `quiet` option so as to receive diagnostic output.

**Comment by skohlbr** [comment]
Point taken, posted to the ML. At this point I'm still on the fence if my issue is a tech support query or a issue report :)
