### ISSUE TITLE
pip fails due to missing boost/python.hpp

### ISSUE THREAD

**Issue by skane88** [inducer/meshpy#34]
Hi, I cannot install meshpy on my Windows 10 machine due to the following error:

```src/cpp/wrap_triangle.cpp(2): fatal error C1083: Cannot open include file: 'boost/python.hpp': No such file or directory```

This seems to be because the boost libraries are missing. When I downloaded the source from github, the bpl-subset directory was empty. Is this the problem? I tried downloading the bpl-subset contents and putting in the appropriate path, then running setup.py, but this didn't help either...

I have Visual Studio 2017 community edition installed which I think is being used as the cpp compiler.

Any clues as to how I could install would be appreciated.

Thanks.

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

Don't download the github tarball. Use `git clone --recursive`.

**Comment by skane88** [comment]
Sorry for polluting your issues tracker - will use the mailing list next time. Note that ``git clone --recursive`` appears to have done the trick. Thank you for the help.
