### ISSUE TITLE
tetrahedral mesh from 3d numpy array

### ISSUE THREAD

**Issue by anildadj** [inducer/meshpy#36]
Hi,

My structure of interest is bounded in 3d numpy boolean array (m x n x p), such that it holds a 1(True) for the structure of interest and a 0(False) elsewhere.

Can this be volume-meshed (tetrahedrally) in meshpy?

Any help is appreciated.

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.
