### ISSUE TITLE
Incompatible with python 3.7?

### ISSUE THREAD

**Issue by codingcatgirl** [inducer/meshpy#37]
When installing meshpy on python 3.7 i get the following compiler error:

```
bpl-subset/bpl_subset/libs/python/src/converter/builtin_converters.cpp:51:35: error: invalid conversion from ‘const void*’ to ‘void*’
```

It doesn't happen when i install it with python 3.6, so it looks like some kind of compatibility issue. It would appreciate if this was fixed, thanks! :)

**Comment by inducer** [comment]
For meshpy, I've decided to go the slightly more heavy-handed (but likely more long-term sustainable) route of switching out boost.python for pybind11. An initial branch that does this can be found here:

https://gitlab.tiker.net/inducer/meshpy/merge_requests/1

It would be fantastic if you could test this out and report back.

**Comment by inducer** [comment]
The pybind11 branch (aka the new master) passes its CI on 3.7, so I'll close this: https://gitlab.tiker.net/inducer/meshpy/-/jobs/62421.
