### ISSUE TITLE
meshpy missing dependencies gcc and pybind11 with 'conda install meshpy'

### ISSUE THREAD

**Issue by puiseux** [inducer/meshpy#38]
as i say in the title, when i tried to `$ pip install meshpy`, 
1. i had an error with libstd++.h (??) I dont remember the exact name of .h missing)
2. i installed gcc : `$ conda install gcc`
3.  Then i tried `$ pip uninstall meshpy` followed by `$ pip install meshpy` the installation complains about some `clang++` and `pybind11` missing
4. I installed `pybind11` with `$ conda install pybind11`
5. finally `$ pip uninstall conda` followed by `$ pip install conda` succeeded.
and that's it, meshpy is installed

**Comment by inducer** [comment]
Thanks for your report.

> conda install meshpy

meshpy is not in any conda repo as far as I know.

The README says:

> MeshPy has no dependencies other than a C++ compiler 

I've updated that to include pybind11: 56a4eea5d3f8931798bb92d589a049efa650335e
