### ISSUE TITLE
TetGen Segmentation fault 

### ISSUE THREAD

**Issue by NataCalc** [inducer/meshpy#40]
[tetGen_mesh_sizing_function_Scaphoid_Lunate.m.zip](https://github.com/inducer/meshpy/files/2843679/tetGen_mesh_sizing_function_Scaphoid_Lunate.m.zip)

[Scaphoid_improved_surface.stl.zip](https://github.com/inducer/meshpy/files/2843681/Scaphoid_improved_surface.stl.zip)

I am using TetGen to create the mesh for STL file. While running TetGen in MatLab I get following error

`Warning:  The 1-th region point lies outside the convex hull.
"/Users/s2986149/Desktop/GIBBON/lib_ext/tetGen/mac64/tetgen" -pq1.2AaY "/Users/s2986149/Desktop/GIBBON/data/temp/tetgenmodel.smesh": Segmentation fault
--- Done --- 08-Feb-2019 14:58:06
 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
--- Importing TetGen files --- 08-Feb-2019 14:58:06
Warning: /Users/s2986149/Desktop/GIBBON/data/temp/tetgenmodel.1.node import unsuccesful 
> In importTETGEN (line 29)
  In runTetGen (line 345)
  In tetGen_mesh_sizing_function_Scaphoid_Lunate (line 79) 
--- Done --- 08-Feb-2019 14:58:06`

I will appreciate any comments on it. 
Cheers,
NataCalc

**Comment by inducer** [comment]
I cannot support tetgen itself. Please reproduce the issue with command line tetgen and contact tetgen's author.
