### ISSUE TITLE
Add matplotlib support for 1D e 2D mesh

### ISSUE THREAD

**Issue by jalfonsi** [inducer/meshpy#42]
I'd like to define and plot polygonal meshes easily in Python as I've done here with Wolfram Language
http://demonstrations.wolfram.com/ColoringTwoDimensionalQuasicrystalTilingsUsingAMeshBasedMeth/
For 3D meshes I'd like to use Ipyvolume
https://github.com/maartenbreddels/ipyvolume
which is better integrated with Jupyter

**Comment by inducer** [comment]
Sure, that sounds fantastic. If you produce any tools that you feel might be of use to users of MeshPy, feel free to send a PR.

**Comment by jalfonsi** [comment]
Is it possible to have mesh objects that could be easily displayed within those software, without using export to file?

**Comment by inducer** [comment]
Whatever you decide. I'd be happy to consider a PR.

**Comment by jalfonsi** [comment]
Actually I was asking you to add such implementation, I'm just a user, I may help with testing.

**Comment by inducer** [comment]
Sorry, no.
