### ISSUE TITLE
No module named "meshpy._internals"

### ISSUE THREAD

**Issue by junfeng-chen** [inducer/meshpy#43]
This module is imported in meshpy.triangle and meshpy.tet, but I cannot find it in meshpy. How come this import error? I checked the git, it does not exists either.

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

**Comment by jwwang0-0** [comment]
Hi,

Sorry I am not sure if I should reopen this discussion but I got the same error. My meshpy version is 2020.1 with python3 and there is no mesh._internals exist. Do I miss anything to install?
