### ISSUE TITLE
How to make 2D mesh?

### ISSUE THREAD

**Issue by JonasRSV** [inducer/meshpy#46]
I find myself needing to create a mesh, I have never really been working with this kind of software before.  

I though this should work 

```python
from meshpy.triangle import MeshInfo, build, write_gnuplot_mesh

meshinfo = MeshInfo()

meshinfo.set_points([(0, 0), (1, 0), (1, 1), (0, 1)])
meshinfo.set_facets([[0, 1, 2, 3]])

result = build(meshinfo, verbose=True)
write_gnuplot_mesh("plot", result)
```

Basically the result I was hoping for was to get the square subdivided by triangles. But the program threw this error

```bash
Traceback (most recent call last):
  File "/home/jonas/tmp/testmeshpy/test.py", line 6, in <module>
    meshinfo.set_facets([[0, 1, 2, 3]])
  File "/home/jonas/tmp/testmeshpy/.venv/lib/python3.6/site-packages/meshpy/triangle.py", line 54, in set_facets
    self.facets[i] = facet
ValueError: value must be a sequence of length self.unit
```

Could you please provide a 2D example, such as the 3D one provided here? https://mathema.tician.de/software/meshpy/. For a new-comer I find it very difficulty understanding the terminology and the documentation, I am for example assuming that a facet is a surface? 

My logic for the code above is that I am assuming that with set_points i define the edges of my surfaces and then with set_facets i define the points that make up some surface?

**Comment by inducer** [comment]
Try [this](https://github.com/inducer/meshpy/blob/master/examples/test_triangle.py) and then more generally the [whole folder full of examples](https://github.com/inducer/meshpy/tree/master/examples).  The [tests](https://github.com/inducer/meshpy/blob/master/test/test_meshpy.py) can also serve as examples.
